import { z } from 'zod';
export declare const askSchema: z.ZodObject<{
    id: z.ZodString;
    description: z.ZodString;
    createdAt: z.ZodType<import("../utils/TimestampStub").TimestampStub, z.ZodTypeDef, import("../utils/TimestampStub").TimestampStub>;
    updatedAt: z.ZodType<import("../utils/TimestampStub").TimestampStub, z.ZodTypeDef, import("../utils/TimestampStub").TimestampStub>;
    expiredAt: z.ZodOptional<z.ZodType<import("../utils/TimestampStub").TimestampStub, z.ZodTypeDef, import("../utils/TimestampStub").TimestampStub>>;
    fulfilledAt: z.ZodOptional<z.ZodType<import("../utils/TimestampStub").TimestampStub, z.ZodTypeDef, import("../utils/TimestampStub").TimestampStub>>;
    fulfilledByUid: z.ZodOptional<z.ZodString>;
    source: z.ZodEnum<["whatsapp", "web"]>;
    responseId: z.ZodOptional<z.ZodString>;
    communityId: z.ZodString;
    communityName: z.ZodOptional<z.ZodString>;
    introductionRequestedFor: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    introductionBlurb: z.ZodOptional<z.ZodString>;
    introductionSentTo: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    introductionSentAt: z.ZodOptional<z.ZodType<import("../utils/TimestampStub").TimestampStub, z.ZodTypeDef, import("../utils/TimestampStub").TimestampStub>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    description: string;
    createdAt: import("../utils/TimestampStub").TimestampStub;
    updatedAt: import("../utils/TimestampStub").TimestampStub;
    source: "whatsapp" | "web";
    communityId: string;
    expiredAt?: import("../utils/TimestampStub").TimestampStub | undefined;
    fulfilledAt?: import("../utils/TimestampStub").TimestampStub | undefined;
    fulfilledByUid?: string | undefined;
    responseId?: string | undefined;
    communityName?: string | undefined;
    introductionRequestedFor?: string[] | undefined;
    introductionBlurb?: string | undefined;
    introductionSentTo?: string[] | undefined;
    introductionSentAt?: import("../utils/TimestampStub").TimestampStub | undefined;
}, {
    id: string;
    description: string;
    createdAt: import("../utils/TimestampStub").TimestampStub;
    updatedAt: import("../utils/TimestampStub").TimestampStub;
    source: "whatsapp" | "web";
    communityId: string;
    expiredAt?: import("../utils/TimestampStub").TimestampStub | undefined;
    fulfilledAt?: import("../utils/TimestampStub").TimestampStub | undefined;
    fulfilledByUid?: string | undefined;
    responseId?: string | undefined;
    communityName?: string | undefined;
    introductionRequestedFor?: string[] | undefined;
    introductionBlurb?: string | undefined;
    introductionSentTo?: string[] | undefined;
    introductionSentAt?: import("../utils/TimestampStub").TimestampStub | undefined;
}>;
export type Ask = z.infer<typeof askSchema>;
