"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.linkedinUserSchema = void 0;
const zod_1 = require("zod");
// Zod schema for LinkedinUser
exports.linkedinUserSchema = zod_1.z.object({
    accomplishment_patents: zod_1.z.array(zod_1.z.any()),
    country: zod_1.z.string(),
    occupation: zod_1.z.string(),
    education: zod_1.z.array(zod_1.z.any()),
    gender: zod_1.z.string(),
    city: zod_1.z.string(),
    people_also_viewed: zod_1.z.array(zod_1.z.any()),
    birth_date: zod_1.z.string().nullable(),
    inferred_salary: zod_1.z.object({
        min: zod_1.z.number().nullable(),
        max: zod_1.z.number().nullable(),
    }),
    background_cover_image_url: zod_1.z.string(),
    industry: zod_1.z.string(),
    follower_count: zod_1.z.number().nullable(),
    recommendations: zod_1.z.array(zod_1.z.string()),
    skills: zod_1.z.array(zod_1.z.string()),
    accomplishment_publications: zod_1.z.array(zod_1.z.any()),
    extra: zod_1.z.object({
        github_profile_id: zod_1.z.string().nullable(),
        twitter_profile_id: zod_1.z.string().nullable(),
        facebook_profile_id: zod_1.z.string().nullable(),
    }),
    personal_numbers: zod_1.z.array(zod_1.z.any()),
    state: zod_1.z.string(),
    volunteer_work: zod_1.z.array(zod_1.z.any()),
    public_identifier: zod_1.z.string(),
    profile_pic_url: zod_1.z.string(),
    first_name: zod_1.z.string(),
    headline: zod_1.z.string(),
    connections: zod_1.z.number(),
    summary: zod_1.z.string(),
    similarly_named_users: zod_1.z.array(zod_1.z.any()),
    languages: zod_1.z.array(zod_1.z.string()),
    accomplishment_courses: zod_1.z.array(zod_1.z.any()),
    groups: zod_1.z.array(zod_1.z.any()),
    last_name: zod_1.z.string(),
    certifications: zod_1.z.array(zod_1.z.any()),
    experiences: zod_1.z.array(zod_1.z.any()),
    country_full_name: zod_1.z.string(),
    full_name: zod_1.z.string(),
    accomplishment_organisations: zod_1.z.array(zod_1.z.any()),
    activities: zod_1.z.array(zod_1.z.any()),
    personal_emails: zod_1.z.array(zod_1.z.string()),
    accomplishment_test_scores: zod_1.z.array(zod_1.z.any()),
    interests: zod_1.z.array(zod_1.z.any()),
    articles: zod_1.z.array(zod_1.z.any()),
    accomplishment_projects: zod_1.z.array(zod_1.z.any()),
    accomplishment_honors_awards: zod_1.z.array(zod_1.z.any()),
});
