import { z } from 'zod';
export declare const linkedinProfileSchema: z.ZodObject<{
    accomplishment_patents: z.ZodArray<z.ZodAny, "many">;
    country: z.ZodString;
    occupation: z.ZodString;
    education: z.ZodArray<z.ZodAny, "many">;
    gender: z.ZodString;
    city: z.ZodString;
    people_also_viewed: z.ZodArray<z.ZodAny, "many">;
    birth_date: z.ZodNullable<z.ZodString>;
    inferred_salary: z.ZodObject<{
        min: z.ZodNullable<z.ZodNumber>;
        max: z.ZodNullable<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        min: number | null;
        max: number | null;
    }, {
        min: number | null;
        max: number | null;
    }>;
    background_cover_image_url: z.ZodString;
    industry: z.ZodString;
    follower_count: z.ZodNullable<z.ZodNumber>;
    recommendations: z.ZodArray<z.ZodString, "many">;
    skills: z.ZodArray<z.ZodString, "many">;
    accomplishment_publications: z.ZodArray<z.ZodAny, "many">;
    extra: z.ZodObject<{
        github_profile_id: z.ZodNullable<z.ZodString>;
        twitter_profile_id: z.ZodNullable<z.ZodString>;
        facebook_profile_id: z.ZodNullable<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        github_profile_id: string | null;
        twitter_profile_id: string | null;
        facebook_profile_id: string | null;
    }, {
        github_profile_id: string | null;
        twitter_profile_id: string | null;
        facebook_profile_id: string | null;
    }>;
    personal_numbers: z.ZodArray<z.ZodAny, "many">;
    state: z.ZodString;
    volunteer_work: z.ZodArray<z.ZodAny, "many">;
    public_identifier: z.ZodString;
    profile_pic_url: z.ZodString;
    first_name: z.ZodString;
    headline: z.ZodString;
    connections: z.ZodNumber;
    summary: z.ZodString;
    similarly_named_profiles: z.ZodArray<z.ZodAny, "many">;
    languages: z.ZodArray<z.ZodString, "many">;
    accomplishment_courses: z.ZodArray<z.ZodAny, "many">;
    groups: z.ZodArray<z.ZodAny, "many">;
    last_name: z.ZodString;
    certifications: z.ZodArray<z.ZodAny, "many">;
    experiences: z.ZodArray<z.ZodAny, "many">;
    country_full_name: z.ZodString;
    full_name: z.ZodString;
    accomplishment_organisations: z.ZodArray<z.ZodAny, "many">;
    activities: z.ZodArray<z.ZodAny, "many">;
    personal_emails: z.ZodArray<z.ZodString, "many">;
    accomplishment_test_scores: z.ZodArray<z.ZodAny, "many">;
    interests: z.ZodArray<z.ZodAny, "many">;
    articles: z.ZodArray<z.ZodAny, "many">;
    accomplishment_projects: z.ZodArray<z.ZodAny, "many">;
    accomplishment_honors_awards: z.ZodArray<z.ZodAny, "many">;
}, "strip", z.ZodTypeAny, {
    state: string;
    accomplishment_patents: any[];
    country: string;
    occupation: string;
    education: any[];
    gender: string;
    city: string;
    people_also_viewed: any[];
    birth_date: string | null;
    inferred_salary: {
        min: number | null;
        max: number | null;
    };
    background_cover_image_url: string;
    industry: string;
    follower_count: number | null;
    recommendations: string[];
    skills: string[];
    accomplishment_publications: any[];
    extra: {
        github_profile_id: string | null;
        twitter_profile_id: string | null;
        facebook_profile_id: string | null;
    };
    personal_numbers: any[];
    volunteer_work: any[];
    public_identifier: string;
    profile_pic_url: string;
    first_name: string;
    headline: string;
    connections: number;
    summary: string;
    similarly_named_profiles: any[];
    languages: string[];
    accomplishment_courses: any[];
    groups: any[];
    last_name: string;
    certifications: any[];
    experiences: any[];
    country_full_name: string;
    full_name: string;
    accomplishment_organisations: any[];
    activities: any[];
    personal_emails: string[];
    accomplishment_test_scores: any[];
    interests: any[];
    articles: any[];
    accomplishment_projects: any[];
    accomplishment_honors_awards: any[];
}, {
    state: string;
    accomplishment_patents: any[];
    country: string;
    occupation: string;
    education: any[];
    gender: string;
    city: string;
    people_also_viewed: any[];
    birth_date: string | null;
    inferred_salary: {
        min: number | null;
        max: number | null;
    };
    background_cover_image_url: string;
    industry: string;
    follower_count: number | null;
    recommendations: string[];
    skills: string[];
    accomplishment_publications: any[];
    extra: {
        github_profile_id: string | null;
        twitter_profile_id: string | null;
        facebook_profile_id: string | null;
    };
    personal_numbers: any[];
    volunteer_work: any[];
    public_identifier: string;
    profile_pic_url: string;
    first_name: string;
    headline: string;
    connections: number;
    summary: string;
    similarly_named_profiles: any[];
    languages: string[];
    accomplishment_courses: any[];
    groups: any[];
    last_name: string;
    certifications: any[];
    experiences: any[];
    country_full_name: string;
    full_name: string;
    accomplishment_organisations: any[];
    activities: any[];
    personal_emails: string[];
    accomplishment_test_scores: any[];
    interests: any[];
    articles: any[];
    accomplishment_projects: any[];
    accomplishment_honors_awards: any[];
}>;
export type LinkedinProfile = z.infer<typeof linkedinProfileSchema>;
