import * as Factory from 'factory.ts';
import { TimestampStub } from '../utils/TimestampStub';
export declare const makeAssessmentFactory: (TimestampKlass: typeof TimestampStub) => Factory.Sync.Factory<{
    createdAt: TimestampStub;
    updatedAt: TimestampStub;
    assessmentRequestId: string;
    seekerResponseId: string;
    seekerAskId: string;
    providerResponseId: string;
    runId: string;
    score: number;
    explanation: string;
    communityId: string;
    humanScore?: number | undefined;
    isSelected?: boolean | undefined;
    introRequestedAt?: TimestampStub | undefined;
    introRequestText?: string | undefined;
    communityName?: string | undefined;
    providerName?: string | undefined;
    providerEmail?: string | undefined;
    providerHeadline?: string | undefined;
    providerPhotoStoragePath?: string | undefined;
    seekerName?: string | undefined;
    seekerEmail?: string | undefined;
    askSummary?: string | undefined;
}, ("createdAt" | "updatedAt" | "assessmentRequestId" | "seekerResponseId" | "seekerAskId" | "providerResponseId" | "runId" | "score" | "explanation" | "communityId") | ("humanScore" | "isSelected" | "introRequestedAt" | "introRequestText" | "communityName" | "providerName" | "providerEmail" | "providerHeadline" | "providerPhotoStoragePath" | "seekerName" | "seekerEmail" | "askSummary")>;
